// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/v1/ingestion.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestLogRequest) Reset() {
	*x = IngestLogRequest{}
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogRequest) ProtoMessage() {}

func (x *IngestLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogRequest.ProtoReflect.Descriptor instead.
func (*IngestLogRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *IngestLogRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestLogRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IngestLogRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IngestLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestLogResponse) Reset() {
	*x = IngestLogResponse{}
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogResponse) ProtoMessage() {}

func (x *IngestLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogResponse.ProtoReflect.Descriptor instead.
func (*IngestLogResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *IngestLogResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_v1_ingestion_proto protoreflect.FileDescriptor

const file_api_proto_v1_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/ingestion.proto\x12\x16omniguard.ingestion.v1\"X\n" +
	"\x10IngestLogRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"H\n" +
	"\x11IngestLogResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2t\n" +
	"\x10IngestionService\x12`\n" +
	"\tIngestLog\x12(.omniguard.ingestion.v1.IngestLogRequest\x1a).omniguard.ingestion.v1.IngestLogResponseB9Z7github.com/omniguard/ingestion/api/proto/v1;ingestionv1b\x06proto3"

var (
	file_api_proto_v1_ingestion_proto_rawDescOnce sync.Once
	file_api_proto_v1_ingestion_proto_rawDescData []byte
)

func file_api_proto_v1_ingestion_proto_rawDescGZIP() []byte {
	file_api_proto_v1_ingestion_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_ingestion_proto_rawDesc), len(file_api_proto_v1_ingestion_proto_rawDesc)))
	})
	return file_api_proto_v1_ingestion_proto_rawDescData
}

var file_api_proto_v1_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_ingestion_proto_goTypes = []any{
	(*IngestLogRequest)(nil),  // 0: omniguard.ingestion.v1.IngestLogRequest
	(*IngestLogResponse)(nil), // 1: omniguard.ingestion.v1.IngestLogResponse
}
var file_api_proto_v1_ingestion_proto_depIdxs = []int32{
	0, // 0: omniguard.ingestion.v1.IngestionService.IngestLog:input_type -> omniguard.ingestion.v1.IngestLogRequest
	1, // 1: omniguard.ingestion.v1.IngestionService.IngestLog:output_type -> omniguard.ingestion.v1.IngestLogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_ingestion_proto_init() }
func file_api_proto_v1_ingestion_proto_init() {
	if File_api_proto_v1_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_ingestion_proto_rawDesc), len(file_api_proto_v1_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_ingestion_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_ingestion_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_ingestion_proto_msgTypes,
	}.Build()
	File_api_proto_v1_ingestion_proto = out.File
	file_api_proto_v1_ingestion_proto_goTypes = nil
	file_api_proto_v1_ingestion_proto_depIdxs = nil
}
