services:
  # Message Broker: Kafka
  zookeeper:
    image: zookeeper:3.9
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # Search Engine: OpenSearch
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - cluster.name=omniguard-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=false
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD:-Complex_Password_123!}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"

  # Analytics: ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # Cache: Redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  # Relational DB: PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=omniguard_admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-RotateMe_2025_Secret!}
      - POSTGRES_DB=omniguard
    ports:
      - "5432:5432"

  # Identity: Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=superadmin
      - KEYCLOAK_ADMIN_PASSWORD=Strong_Admin_Pass_99!
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # Observability
  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  default:
    name: omniguard-network
