global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'omniguard-services'
    static_configs:
      - targets: ['identity:8081', 'ingestion:8082', 'search:8083', 'correlation:8084', 'alerting:8085', 'case-management:8086']
